spring:
  application:
    name: currency-exchange-api
  datasource:
    url: jdbc:h2:file:./data/currencydb
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
  h2:
    console:
      enabled: false

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    org.springframework: INFO
